
name: DepthAI ROS Testing
on:
  workflow_dispatch:
  push:
    branches:
      - kilted_testing
      - kilted
  pull_request:
    branches:
      - kilted

env:
  ROS_DISTRO: kilted

jobs:
  run_tests:
    uses: ./.github/workflows/test_child.yml
    secrets:
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      HIL_PAT_TOKEN: ${{ secrets.HIL_PAT_TOKEN }}
